package server

import (
	"encoding/json"
	"net/http"
	"sort"
	"strconv"
	"strings"
	"time"

	"emby-go/internal/librarywatch"

	"github.com/gin-gonic/gin"
)

func (a *App) users(c *gin.Context) {
	users := []gin.H{}
	if !strings.EqualFold(c.Query("IsHidden"), "true") && !strings.EqualFold(c.Query("IsDisabled"), "true") && !strings.EqualFold(c.Query("IsGuest"), "true") {
		users = append(users, a.userDto())
	}
	c.JSON(http.StatusOK, users)
}

func (a *App) virtualFolders(c *gin.Context) {
	libraries, err := a.db.Libraries()
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	folders := make([]gin.H, 0, len(libraries))
	for _, library := range libraries {
		id := externalLibraryID(library.ID)
		folders = append(folders, gin.H{
			"Name": library.Name, "Locations": []string{library.Path},
			"CollectionType": "movies", "ItemId": id, "Id": id,
			"LibraryOptions": gin.H{
				"ContentType": "movies", "PathInfos": []gin.H{{"Path": library.Path}},
				"EnableRealtimeMonitor":        !a.cfg.DisableLibraryMonitor && a.cfg.MonitorMode() == librarywatch.ModeRealtime,
				"EnableChapterImageExtraction": false, "ExtractChapterImagesDuringLibraryScan": false,
			},
		})
	}
	c.JSON(http.StatusOK, folders)
}

// ThumbnailSet describes timeline preview frames, not poster/backdrop images.
// No preview frames are generated by this server, so available items have an
// empty set. Checking existence keeps unknown and hidden item IDs as 404.
func (a *App) thumbnailSet(c *gin.Context) {
	id, err := strconv.ParseInt(c.Param("id"), 10, 64)
	part := 0
	if err != nil {
		var ok bool
		id, part, ok = parseVirtualPartID(c.Param("id"))
		if !ok {
			c.JSON(http.StatusNotFound, gin.H{"error": "not found"})
			return
		}
	}
	movie, err := a.db.Movie(id)
	if err != nil || !movie.IsVisible() || (part > 0 && part-2 >= len(movie.AdditionalParts)) {
		c.JSON(http.StatusNotFound, gin.H{"error": "not found"})
		return
	}
	c.JSON(http.StatusOK, gin.H{"AspectRatio": 0.0, "Thumbnails": []gin.H{}})
}

func (a *App) tagsList(c *gin.Context)        { a.catalogList(c, "Tag") }
func (a *App) studios(c *gin.Context)         { a.catalogList(c, "Studio") }
func (a *App) years(c *gin.Context)           { a.catalogList(c, "Year") }
func (a *App) officialRatings(c *gin.Context) { a.catalogList(c, "OfficialRating") }

func (a *App) catalogList(c *gin.Context, kind string) {
	if userID := c.Query("UserId"); userID != "" && userID != "1" {
		c.JSON(http.StatusNotFound, gin.H{"error": "user not found"})
		return
	}
	libraryID, collection := parseParentScope(c.Query("ParentId"))
	parent := strings.TrimSpace(c.Query("ParentId"))
	if parent != "" && parent != "0" && libraryID == 0 && collection == "" {
		c.JSON(http.StatusNotFound, gin.H{"error": "parent not found"})
		return
	}
	if libraryID != 0 {
		if _, err := a.db.Library(libraryID); err != nil {
			c.JSON(http.StatusNotFound, gin.H{"error": "parent not found"})
			return
		}
	}
	start, _ := strconv.Atoi(c.DefaultQuery("StartIndex", "0"))
	limit, _ := strconv.Atoi(c.DefaultQuery("Limit", "1000"))
	if start < 0 {
		start = 0
	}
	if limit < 1 || limit > 1000 {
		limit = 1000
	}
	// Only Movie/Video exist in this library model. Do not offer movie-derived
	// filters when a client explicitly browses an unsupported media type.
	if !catalogIncludesMovies(c) {
		a.emptyItems(c)
		return
	}
	term := strings.ToLower(strings.TrimSpace(c.Query("SearchTerm")))
	prefix := strings.ToLower(c.Query("NameStartsWith"))
	minimum := strings.ToLower(c.Query("NameStartsWithOrGreater"))
	maximum := strings.ToLower(c.Query("NameLessThan"))
	desc := strings.EqualFold(c.Query("SortOrder"), "Descending")
	key := responseKey("catalog", a.cacheScope(libraryID), kind, collection, start, limit, term, prefix, minimum, maximum, desc, c.Query("EnableImages"))
	a.cachedResponse(c, key, 30*time.Second, func() ([]byte, error) {
		names, err := a.db.CatalogNames(kind, libraryID, collection)
		if err != nil {
			return nil, err
		}
		filtered := make([]string, 0, len(names))
		for _, name := range names {
			lower := strings.ToLower(name)
			if (term == "" || strings.Contains(lower, term)) && (prefix == "" || strings.HasPrefix(lower, prefix)) && (minimum == "" || lower >= minimum) && (maximum == "" || lower < maximum) {
				filtered = append(filtered, name)
			}
		}
		sort.Slice(filtered, func(i, j int) bool {
			left, right := strings.ToLower(filtered[i]), strings.ToLower(filtered[j])
			if kind == "Year" {
				ly, _ := strconv.Atoi(left)
				ry, _ := strconv.Atoi(right)
				if ly != ry {
					if desc {
						return ly > ry
					}
					return ly < ry
				}
			}
			if left == right {
				left, right = filtered[i], filtered[j]
			}
			if desc {
				return left > right
			}
			return left < right
		})
		total := len(filtered)
		pageStart := min(start, total)
		pageEnd := pageStart + min(limit, total-pageStart)
		items := make([]gin.H, 0, pageEnd-pageStart)
		for _, name := range filtered[pageStart:pageEnd] {
			item := gin.H{"Name": name}
			switch kind {
			case "Tag":
				item["Id"] = entityId(kind, name)
			case "Year":
				item["Id"] = name
			case "Studio":
				item["Id"], item["Type"], item["IsFolder"], item["ServerId"] = entityId(kind, name), kind, true, a.serverID
				item["ImageTags"] = gin.H{}
				if !strings.EqualFold(c.Query("EnableImages"), "false") {
					if poster := a.entityPosterPath(kind, name); poster != "" {
						item["ImageTags"] = gin.H{"Primary": a.posterTag(poster)}
					}
				}
			}
			items = append(items, item)
		}
		return json.Marshal(gin.H{"Items": items, "TotalRecordCount": total, "StartIndex": start})
	})
}

func catalogIncludesMovies(c *gin.Context) bool {
	for _, kind := range splitQueryTypes(c.Query("ExcludeItemTypes")) {
		if strings.EqualFold(kind, "Movie") || strings.EqualFold(kind, "Video") {
			return false
		}
	}
	include := splitQueryTypes(c.Query("IncludeItemTypes"))
	if len(include) > 0 {
		found := false
		for _, kind := range include {
			if strings.EqualFold(kind, "Movie") || strings.EqualFold(kind, "Video") {
				found = true
			}
		}
		if !found {
			return false
		}
	}
	media := splitQueryTypes(c.Query("MediaTypes"))
	if len(media) > 0 {
		for _, kind := range media {
			if strings.EqualFold(kind, "Video") {
				return true
			}
		}
		return false
	}
	return true
}
