<script setup lang="ts">
import { onScopeDispose, reactive, ref, watch } from 'vue'; import { scheduledApi, type ScheduledTask, type ScheduledPayload } from '../../api/scheduled'; import type { LibraryDto } from '../../api/contracts'; import { fmtTime } from '../../lib/format';
const props = defineProps<{ editing: ScheduledTask|null; libraries: LibraryDto[]; types: Record<string,string>; submitting: boolean }>(); const emit = defineEmits<{ submit: [payload: ScheduledPayload]; cancelEdit: [] }>();
const draft = reactive({name:'',type:'scan',cron:'',library:0,status:'success',onlyMissing:true,overwrite:'',limit:0,enabled:true}); const preview = ref('标准 5 段（分 时 日 月 周）或 @daily/@hourly 等描述符；留空无法保存。'), invalid = ref(false);
const presets = [['每小时','0 * * * *'],['每天 03:00','0 3 * * *'],['每周一 04:00','0 4 * * 1'],['每月 1 日 05:00','0 5 1 * *']];
let timer:ReturnType<typeof setTimeout>|undefined, controller:AbortController|undefined, epoch=0;
watch(() => props.editing?.id, () => { const item=props.editing; let params:Record<string,unknown>={}; try { const p=JSON.parse(item?.params || '{}'); if (p && typeof p==='object' && !Array.isArray(p)) params=p; } catch { /* legacy malformed params use defaults */ }
  Object.assign(draft,{name:item?.name||'',type:item?.type||'scan',cron:item?.cron||'',library:typeof params.library_id==='number'?params.library_id:0,status:typeof params.status==='string'?params.status:'success',onlyMissing:params.only_missing!==false,overwrite:typeof params.overwrite==='boolean'?String(params.overwrite):'',limit:typeof params.limit==='number'?params.limit:0,enabled:item?.enabled??true});
}, {immediate:true});
watch(() => draft.cron, () => { clearTimeout(timer); controller?.abort(); const current=++epoch, cron=draft.cron.trim(); invalid.value=false; if(!cron) { preview.value='请输入 cron 表达式。'; return; } preview.value='正在校验表达式…'; timer=setTimeout(async()=>{ controller=new AbortController(); try { const r=await scheduledApi.validate(cron,controller.signal); if(current!==epoch) return; invalid.value=!r.valid; preview.value=r.valid?'接下来执行：'+r.next_runs.map(fmtTime).join(' · '):'表达式非法：'+r.error; } catch(cause) { if(current===epoch) {invalid.value=true;preview.value=cause instanceof Error?cause.message:'校验失败';} } },300); }, {immediate:true});
function submit() { if(props.submitting) return; const params:Record<string,unknown>={}; if(draft.type!=='reindex') params.library_id=Number(draft.library)||0; if(draft.type==='probe') {params.status=draft.status;params.only_missing=draft.onlyMissing;} if(draft.type==='scrape') {params.only_missing=draft.onlyMissing;if(draft.overwrite!=='') params.overwrite=draft.overwrite==='true';} if(['probe','scrape','scrape_avatars'].includes(draft.type)&&draft.limit>0) params.limit=Number(draft.limit); emit('submit',{name:draft.name.trim(),type:draft.type,cron:draft.cron.trim(),enabled:draft.enabled,params}); }
onScopeDispose(()=>{epoch++;clearTimeout(timer);controller?.abort();});
</script>
<template><section class="panel"><div class="panel-head"><h2>{{editing?'编辑计划任务':'新建计划任务'}}</h2><div v-if="editing" class="panel-actions"><button id="sched-cancel" class="btn btn-sm" :disabled="submitting" @click="emit('cancelEdit')">取消编辑</button></div></div><p class="hint" style="margin:0 0 14px">到点自动执行，保存后立即生效（无需重启）。同一任务上一轮未结束时跳过本次并记录。</p><form id="sched-form" class="field-grid" @submit.prevent="submit">
<div class="field"><label for="s-name">名称 *</label><input id="s-name" v-model="draft.name" required placeholder="如 夜间扫库"></div><div class="field"><label for="s-type">任务类型 *</label><select id="s-type" v-model="draft.type"><option v-for="(text,key) in types" :key="key" :value="key">{{text}}</option></select></div><div class="field"><label for="s-cron">cron 表达式 *</label><input id="s-cron" v-model="draft.cron" class="mono" required placeholder="0 3 * * *"></div>
<div class="field" data-show="library" :hidden="draft.type==='reindex'"><label for="s-lib">媒体库</label><select id="s-lib" v-model.number="draft.library"><option :value="0">全部媒体库</option><option v-for="lib in libraries" :key="lib.Id" :value="lib.Id">{{lib.Name}}</option></select></div><div class="field" data-show="probe" :hidden="draft.type!=='probe'"><label for="s-status">影片状态</label><select id="s-status" v-model="draft.status"><option value="success">已入库</option><option value="manual">手动录入</option><option value="">全部</option></select></div><div class="field" data-show="missing" :hidden="!['probe','scrape'].includes(draft.type)"><label>处理范围</label><label class="check"><input id="s-only-missing" v-model="draft.onlyMissing" type="checkbox"> 仅未探测 / 缺失元数据的条目</label></div>
<div v-if="draft.type==='scrape'" class="field"><label for="s-overwrite">覆盖策略</label><select id="s-overwrite" v-model="draft.overwrite"><option value="">使用刮削配置默认值</option><option value="false">只补缺失</option><option value="true">强制覆盖</option></select></div><div v-if="['probe','scrape','scrape_avatars'].includes(draft.type)" class="field"><label for="s-limit">处理上限（0 = 不限制）</label><input id="s-limit" v-model.number="draft.limit" type="number" min="0" step="1"></div>
<div class="field"><label>启用</label><label class="check"><input id="s-enabled" v-model="draft.enabled" type="checkbox"> 保存后参与调度</label></div><div class="field full"><label>常用预设</label><div class="preset-row"><button v-for="[text,expr] in presets" :key="expr" type="button" class="btn btn-sm preset" :data-cron="expr" @click="draft.cron=expr!">{{text}}</button></div></div><p id="s-preview" class="hint full" style="grid-column:1/-1" :style="{color:invalid?'var(--danger)':''}" aria-live="polite">{{preview}}</p><div class="form-foot" style="grid-column:1/-1"><button id="sched-submit" class="btn btn-accent" type="submit" :disabled="submitting">{{submitting?'正在保存…':editing?'保存修改':'新建任务'}}</button></div>
</form></section></template>
