import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';import{mount,flushPromises}from'@vue/test-utils';import{createPinia,disposePinia,setActivePinia,type Pinia}from'pinia';import{scheduledApi,parseScheduled,type ScheduledTask}from'../src/api/scheduled';import ScheduledForm from'../src/components/scheduled/ScheduledForm.vue';import ScheduledPage from'../src/pages/ScheduledPage.vue';import{adminApi}from'../src/api/admin';import{useScheduledStore}from'../src/stores/scheduled';import{apiClient}from'../src/api/client';import fixture from'../../vue-migration/fixtures/json/scheduled.json';
const task:ScheduledTask={id:1,name:'Night',type:'probe',cron:'@daily',params:'{"library_id":2,"status":"","only_missing":false,"limit":4}',enabled:false,next_run:'',last_status:'',last_run_at:'',last_message:''};const cleanups:(()=>void)[]=[];let pinia:Pinia;
beforeEach(()=>{vi.useFakeTimers();pinia=createPinia();setActivePinia(pinia);});afterEach(()=>{cleanups.splice(0).reverse().forEach(fn=>fn());disposePinia(pinia);vi.useRealTimers();});
function form(editing:ScheduledTask|null=null){const w=mount(ScheduledForm,{props:{editing,libraries:[{Id:2,Name:'L',Path:''}],types:fixture.types,submitting:false}});cleanups.push(()=>w.unmount());return w;}
describe('scheduled lifecycle and DTO',()=>{
it('consumes real Go definitions and validates nullable optional fields',()=>{expect(parseScheduled(fixture).items).toEqual([]);expect(parseScheduled({...fixture,items:[task]}).items[0]).toEqual(task);expect(()=>parseScheduled({...fixture,items:[{...task,enabled:'false'}]})).toThrow();});
it('cron POST is explicitly read-only and linked to its form lifetime',async()=>{const req=vi.spyOn(apiClient,'request').mockResolvedValue({valid:true,next_runs:['2026-10-11T00:00:00Z']});const signal=new AbortController().signal;await scheduledApi.validate('@daily',signal);expect(req.mock.calls[0]![1]).toMatchObject({readOnly:true,signal,json:{cron:'@daily'}});});
it('edit backfills explicit false, blank status and limit; type change excludes stale parameters',async()=>{vi.spyOn(scheduledApi,'validate').mockResolvedValue({valid:true,error:'',next_runs:[]});const w=form(task);expect((w.get('#s-only-missing').element as HTMLInputElement).checked).toBe(false);expect((w.get('#s-status').element as HTMLSelectElement).value).toBe('');await w.get('form').trigger('submit');expect(w.emitted('submit')?.[0]?.[0]).toMatchObject({enabled:false,params:{library_id:2,status:'',only_missing:false,limit:4}});await w.get('#s-type').setValue('reindex');expect(w.get('[data-show=library]').attributes('hidden')).toBeDefined();await w.get('form').trigger('submit');expect(w.emitted('submit')?.[1]?.[0]).toMatchObject({type:'reindex',params:{}});});
it('scrape coverage has real default/false/true request states and preserves existing false',async()=>{const w=form({...task,type:'scrape',params:'{"overwrite":false,"only_missing":false}'});await w.get('form').trigger('submit');expect(w.emitted('submit')?.[0]?.[0]).toMatchObject({params:{overwrite:false,only_missing:false}});await w.get('#s-overwrite').setValue('');await w.get('form').trigger('submit');expect((w.emitted('submit')?.[1]?.[0] as any).params).not.toHaveProperty('overwrite');await w.get('#s-overwrite').setValue('true');await w.get('form').trigger('submit');expect(w.emitted('submit')?.[2]?.[0]).toMatchObject({params:{overwrite:true}});});
it('malformed stored params safely fall back, presets validate and unmount clears reads/timers',async()=>{const validate=vi.spyOn(scheduledApi,'validate').mockResolvedValue({valid:false,error:'bad cron',next_runs:[]});const w=form({...task,params:'broken'});await w.get('[data-cron="0 3 * * *"]').trigger('click');await vi.advanceTimersByTimeAsync(300);expect(w.get('#s-preview').text()).toContain('表达式非法：bad cron');expect(validate).toHaveBeenCalledTimes(1);w.unmount();expect(validate.mock.calls[0]![1].aborted).toBe(true);expect(vi.getTimerCount()).toBe(0);});
it('newer cron validation wins even when an aborted old reply arrives later',async()=>{let resolve!:(v:{valid:boolean;error:string;next_runs:string[]})=>void;const late=new Promise<{valid:boolean;error:string;next_runs:string[]}>(r=>{resolve=r;});const validate=vi.spyOn(scheduledApi,'validate').mockReturnValueOnce(late).mockResolvedValueOnce({valid:false,error:'new invalid',next_runs:[]});const w=form();await w.get('#s-cron').setValue('@daily');await vi.advanceTimersByTimeAsync(300);await w.get('#s-cron').setValue('new');await vi.advanceTimersByTimeAsync(300);expect(validate.mock.calls[0]![1].aborted).toBe(true);resolve({valid:true,error:'',next_runs:['old']});await flushPromises();expect(w.get('#s-preview').text()).toContain('new invalid');});
it('page failure retains draft, duplicate submit locks, success clears new form',async()=>{vi.spyOn(scheduledApi,'list').mockResolvedValue({...fixture,items:[]});vi.spyOn(adminApi,'libraries').mockResolvedValue({items:[],total:0});let resolve!:(v:unknown)=>void;const pending=new Promise(r=>{resolve=r;});const save=vi.spyOn(scheduledApi,'save').mockRejectedValueOnce(new Error('invalid')).mockReturnValueOnce(pending);const w=mount(ScheduledPage,{global:{plugins:[pinia]}});cleanups.push(()=>w.unmount());await flushPromises();await w.get('#s-name').setValue('Night');await w.get('#s-cron').setValue('bad');await w.get('form').trigger('submit');await flushPromises();expect((w.get('#s-name').element as HTMLInputElement).value).toBe('Night');await w.get('form').trigger('submit');await w.get('form').trigger('submit');expect(save).toHaveBeenCalledTimes(2);resolve({id:1});await flushPromises();expect((w.get('#s-name').element as HTMLInputElement).value).toBe('');});
it('editing selection persists when a page leaves and returns, cancellation clears it',async()=>{vi.spyOn(scheduledApi,'list').mockResolvedValue({...fixture,items:[task]});vi.spyOn(adminApi,'libraries').mockResolvedValue({items:[],total:0});vi.spyOn(scheduledApi,'validate').mockResolvedValue({valid:true,error:'',next_runs:[]});const state=useScheduledStore();state.editingId=1;let w=mount(ScheduledPage,{global:{plugins:[pinia]}});await flushPromises();expect((w.get('#s-name').element as HTMLInputElement).value).toBe('Night');w.unmount();w=mount(ScheduledPage,{global:{plugins:[pinia]}});cleanups.push(()=>w.unmount());await flushPromises();expect(w.text()).toContain('编辑计划任务');await w.get('#sched-cancel').trigger('click');expect(state.editingId).toBeNull();});
});
