import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'; import { mount, flushPromises } from '@vue/test-utils'; import { createPinia, disposePinia, setActivePinia, type Pinia } from 'pinia';
import { scrapeApi, parsePreview, parseInspect, parseScrapeSettings, type Preview, type Inspect } from '../src/api/scrape'; import { useScrapePreviewStore } from '../src/stores/scrape-preview'; import ScrapePreviewDialog from '../src/components/scrape/ScrapePreviewDialog.vue'; import ScrapeSettingsForm from '../src/components/scrape/ScrapeSettingsForm.vue'; import ScrapePage from '../src/pages/ScrapePage.vue'; import { adminApi } from '../src/api/admin'; import { createApiClient, apiClient } from '../src/api/client';
import settingsFixture from '../../vue-migration/fixtures/json/scrape-settings.json';
const settings=parseScrapeSettings(settingsFixture), candidates=[{provider:'fanza',id:'a',number:'ABF-005',title:'ABF-005 Alpha',score:7.5,thumb:'',exact:true},{provider:'fanza',id:'b',number:'ABF-005',title:'ABF-005 Beta',score:7,thumb:'',exact:true}];
const preview:Preview={movie_id:5,query:'ABF-005',expected_number:'ABF-005',recommended:0,candidates}; const inspect:Inspect={provider:'fanza',id:'a',number:'ABF-005',title:'Alpha',summary:'plot',poster:'',score:7.5,release_date:'2024',runtime:89,overwrite:true,fields:[{key:'title',label:'标题',old:'Old',next:'Alpha',change:true}],images:[{name:'poster.webp',preview:'',exists:true}]};
function deferred<T>(){let resolve!:(v:T)=>void;const promise=new Promise<T>(r=>{resolve=r;});return{promise,resolve};}
let pinia:Pinia;const cleanup:(()=>void)[]=[];beforeEach(()=>{pinia=createPinia();setActivePinia(pinia);});afterEach(()=>{cleanup.splice(0).reverse().forEach(fn=>fn());disposePinia(pinia);});
describe('scrape read-only boundaries and confirmations',()=>{
  it('parses settings and rejects invented or malformed candidate/inspect data',()=>{expect(settings.overwrite).toBe(false);expect(parsePreview(preview).candidates).toHaveLength(2);expect(parseInspect(inspect).overwrite).toBe(true);expect(()=>parsePreview({...preview,recommended:2})).toThrow();expect(()=>parseInspect({...inspect,overwrite:'false'})).toThrow();expect(()=>parseScrapeSettings({...settingsFixture,concurrency:'2'})).toThrow();});
  it('read-only POSTs do not dirty snapshots while real writes still invalidate once',async()=>{const client=createApiClient(vi.fn(async () => new Response('{}')));client.setAuthHandlers({getToken:()=> 'unit',onUnauthorized:vi.fn()});const dirty=vi.fn();client.onWriteSuccess(dirty);await client.request('/api/admin/items/5/scrape/inspect',{auth:'required',method:'POST',readOnly:true,json:{}});expect(dirty).not.toHaveBeenCalled();await client.request('/api/admin/items/5/scrape',{auth:'required',method:'POST',json:{overwrite:false}});expect(dirty).toHaveBeenCalledTimes(1);});
  it('actual adapter marks inspect/test as reads and sends explicit false only on confirmation',async()=>{const request=vi.spyOn(apiClient,'request').mockResolvedValueOnce(inspect).mockResolvedValueOnce({ok:true,detail:'local',elapsed_ms:1}).mockResolvedValueOnce({title:'saved',images:0});const signal=new AbortController().signal;await scrapeApi.inspect(5,'fanza','a',signal);await scrapeApi.test('metatube');await scrapeApi.confirm(5,'fanza','a',false);expect(request.mock.calls[0]![1]).toMatchObject({readOnly:true,signal});expect(request.mock.calls[2]![1]).toMatchObject({json:{provider:'fanza',id:'a',overwrite:false},signal:undefined,readOnly:false});});
  it('closing during preview aborts its read and never inspects or confirms a late result',async()=>{const wait=deferred<Preview>();const read=vi.spyOn(scrapeApi,'preview').mockReturnValue(wait.promise),detail=vi.spyOn(scrapeApi,'inspect'),write=vi.spyOn(scrapeApi,'confirm');const store=useScrapePreviewStore();const pending=store.open(5,vi.fn());store.close();expect(read.mock.calls[0]![1].aborted).toBe(true);wait.resolve(preview);await pending;expect(store.current).toBeNull();expect(detail).not.toHaveBeenCalled();expect(write).not.toHaveBeenCalled();});
  it('candidate switches discard late inspect and close aborts only the read',async()=>{vi.spyOn(scrapeApi,'preview').mockResolvedValue(preview);const late=deferred<Inspect>(),read=vi.spyOn(scrapeApi,'inspect').mockResolvedValueOnce(inspect).mockReturnValueOnce(late.promise).mockResolvedValueOnce({...inspect,id:'b',title:'Beta'});const store=useScrapePreviewStore();await store.open(5,vi.fn());const old=store.select(candidates[0]!);await store.select(candidates[1]!);expect(read.mock.calls[1]![3].aborted).toBe(true);late.resolve(inspect);await old;expect(store.inspect?.title).toBe('Beta');store.close();expect(store.inspect).toBeNull();});
  it('confirmation locks duplicates, preserves explicit false and failure allows retry in the same dialog',async()=>{vi.spyOn(scrapeApi,'preview').mockResolvedValue(preview);vi.spyOn(scrapeApi,'inspect').mockResolvedValue(inspect);const late=deferred<{title:string;images:number}>(),write=vi.spyOn(scrapeApi,'confirm').mockRejectedValueOnce(new Error('failed')).mockReturnValueOnce(late.promise);const confirmed=vi.fn(),store=useScrapePreviewStore();await store.open(5,confirmed);store.overwrite=false;await store.confirm();expect(store.current?.movieId).toBe(5);expect(store.writing).toBe(false);const first=store.confirm();await store.confirm();expect(write).toHaveBeenCalledTimes(2);expect(write.mock.calls[1]).toEqual([5,'fanza','a',false]);late.resolve({title:'saved',images:1});await first;expect(store.current).toBeNull();expect(confirmed).toHaveBeenCalledTimes(1);});
  it('closing during a short write leaves it running but the detail owner guards a later page',async()=>{vi.spyOn(scrapeApi,'preview').mockResolvedValue(preview);vi.spyOn(scrapeApi,'inspect').mockResolvedValue(inspect);const late=deferred<{title:string;images:number}>();vi.spyOn(scrapeApi,'confirm').mockReturnValue(late.promise);let active=true;const refreshed=vi.fn(),store=useScrapePreviewStore();await store.open(5,()=>{if(active)refreshed();});const pending=store.confirm();store.close();active=false;await store.open(6,vi.fn());expect(store.current).toBeNull();late.resolve({title:'saved',images:0});await pending;expect(refreshed).not.toHaveBeenCalled();expect(store.writing).toBe(false);});
  it('Escape cancels dialog only, restores focus and body overflow without writes',async()=>{vi.spyOn(scrapeApi,'preview').mockResolvedValue(preview);vi.spyOn(scrapeApi,'inspect').mockResolvedValue(inspect);const write=vi.spyOn(scrapeApi,'confirm'),trigger=document.createElement('button');document.body.append(trigger);trigger.focus();cleanup.push(()=>trigger.remove());const store=useScrapePreviewStore();await store.open(5,vi.fn());const w=mount(ScrapePreviewDialog,{attachTo:document.body,global:{plugins:[pinia]}});cleanup.push(()=>w.unmount());expect(document.body.style.overflow).toBe('hidden');window.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape'}));await flushPromises();expect(store.current).toBeNull();expect(trigger).toBe(document.activeElement);expect(write).not.toHaveBeenCalled();w.unmount();expect(document.body.style.overflow).toBe('');});
  it('form secrets start blank, preserve failure draft and submit explicit overwrite false',async()=>{const w=mount(ScrapeSettingsForm,{props:{settings:{...settings,metatube_token:'test****',translate:{...settings.translate,api_key:'key****'}},saving:false,testing:new Set<string>()}});cleanup.push(()=>w.unmount());expect((w.get('#sc-token').element as HTMLInputElement).value).toBe('');expect((w.get('#tr-key').element as HTMLInputElement).value).toBe('');await w.get('#sc-url').setValue('http://local');await w.get('form').trigger('submit');expect(w.emitted('save')?.[0]?.[0]).toMatchObject({metatube_url:'http://local',metatube_token:'',overwrite:false,translate:{api_key:''}});await w.setProps({saving:true});expect(w.get('#scrape-save').attributes('disabled')).toBeDefined();expect((w.get('#sc-url').element as HTMLInputElement).value).toBe('http://local');});
  it('page save lock survives departure and a failed save retains entered URL for retry',async()=>{vi.spyOn(scrapeApi,'settings').mockResolvedValue(settings);vi.spyOn(adminApi,'libraries').mockResolvedValue({items:[],total:0});vi.spyOn(scrapeApi,'candidates').mockResolvedValue(0);const late=deferred<typeof settings>(),save=vi.spyOn(scrapeApi,'save').mockRejectedValueOnce(new Error('failed')).mockReturnValueOnce(late.promise);const w=mount(ScrapePage,{global:{plugins:[pinia]}});cleanup.push(()=>w.unmount());await flushPromises();await w.get('#sc-url').setValue('http://local');await w.get('form').trigger('submit');await flushPromises();expect((w.get('#sc-url').element as HTMLInputElement).value).toBe('http://local');await w.get('form').trigger('submit');await w.get('form').trigger('submit');expect(save).toHaveBeenCalledTimes(2);w.unmount();late.resolve(settings);await flushPromises();});
});
