import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { createPinia, disposePinia, setActivePinia, type Pinia } from 'pinia'; import { flushPromises } from '@vue/test-utils';
import { backgroundApi, parseBackgroundProgress } from '../src/api/background'; import { useTasksStore } from '../src/stores/tasks'; import { useToastStore } from '../src/stores/toasts'; import { ApiError } from '../src/api/client';
const idle = parseBackgroundProgress({running:false,total:0,done:0,success:0,skipped:0,failed:0,current:'',cancelled:false});
const running = {...idle,running:true,total:3,started_at:'now'}, ended = {...running,running:false,done:3,success:3,finished_at:'later'};
function deferred<T>() { let resolve!:(v:T)=>void; const promise=new Promise<T>(r=>{resolve=r;});return{promise,resolve}; }
let pinia:Pinia; beforeEach(()=>{vi.useFakeTimers();pinia=createPinia();setActivePinia(pinia);}); afterEach(()=>{disposePinia(pinia);vi.useRealTimers();});
describe('application background lifetimes',()=>{
  it('service reset cannot be announced as a successful completion',async()=>{vi.spyOn(backgroundApi,'progress').mockResolvedValueOnce(running).mockResolvedValue(idle);const tasks=useTasksStore();await tasks.probe.restore();await vi.advanceTimersByTimeAsync(1000);expect(tasks.probe.progress?.error).toContain('服务可能已重启');expect(useToastStore().items.some(t=>t.message.includes('探测完成'))).toBe(false);expect(tasks.revision).toBe(1);expect(tasks.probe.busy).toBe(false);});
  it('parses optional failure/cancellation fields but rejects malformed counters and samples',()=>{expect(idle.failures).toEqual([]);expect(()=>parseBackgroundProgress({...idle,done:'4'})).toThrow();expect(()=>parseBackgroundProgress({...idle,failures:[false]})).toThrow();expect(()=>parseBackgroundProgress({...idle,running:'false'})).toThrow();});
  it('starts once, owns its submit signal and blocks scan/scrape while probe is pending',async()=>{const pending=deferred<{total:number;message:string}>();const start=vi.spyOn(backgroundApi,'start').mockReturnValue(pending.promise);vi.spyOn(backgroundApi,'progress').mockResolvedValue(running);const tasks=useTasksStore();const first=tasks.probe.run({only_missing:true});await flushPromises();expect(tasks.mutationBusy).toBe(true);expect(await tasks.probe.run({})).toBe(false);expect(await tasks.scrape.run({})).toBe(false);expect(await tasks.run()).toBe(false);expect(start).toHaveBeenCalledTimes(1);expect(start.mock.calls[0]![3].aborted).toBe(false);pending.resolve({total:3,message:''});await first;expect(tasks.probe.progress?.running).toBe(true);});
  it('keeps known progress on network errors, retries without overlapping and completes once',async()=>{const pending=deferred<typeof running>();const poll=vi.spyOn(backgroundApi,'progress').mockResolvedValueOnce(running).mockRejectedValueOnce(new TypeError('offline')).mockReturnValueOnce(pending.promise).mockResolvedValue(ended);const tasks=useTasksStore();await tasks.probe.restore();await vi.advanceTimersByTimeAsync(1000);expect(tasks.probe.unavailable).toBe(true);expect(tasks.probe.busy).toBe(true);expect(tasks.revision).toBe(0);await vi.advanceTimersByTimeAsync(2000);await vi.advanceTimersByTimeAsync(20000);expect(poll).toHaveBeenCalledTimes(3);pending.resolve(ended);await flushPromises();expect(tasks.revision).toBe(1);expect(tasks.probe.busy).toBe(false);await tasks.probe.restore();expect(tasks.revision).toBe(1);await vi.advanceTimersByTimeAsync(8000);expect(tasks.probe.visible).toBe(false);});
  it('recognizes a fast accepted job already ended, retains failure samples and does not hide them',async()=>{vi.spyOn(backgroundApi,'start').mockResolvedValue({total:3,message:''});vi.spyOn(backgroundApi,'progress').mockResolvedValue({...ended,success:2,failed:1,failures:['local sample']});const tasks=useTasksStore();await tasks.probe.run({});expect(tasks.revision).toBe(1);expect(tasks.probe.visible).toBe(true);expect(useToastStore().items.some(t=>t.message.includes('失败 1'))).toBe(true);await vi.advanceTimersByTimeAsync(20000);expect(tasks.probe.visible).toBe(true);});
  it('does not announce a historical finished job as new completion on login',async()=>{vi.spyOn(backgroundApi,'progress').mockResolvedValue(ended);const tasks=useTasksStore();await tasks.probe.restore();expect(tasks.probe.visible).toBe(false);expect(tasks.revision).toBe(0);expect(useToastStore().items).toHaveLength(0);});
  it('reports 409 startup honestly, unlocks submit and discovers an existing running job',async()=>{vi.spyOn(backgroundApi,'start').mockRejectedValue(new ApiError('探测任务正在进行中',409));vi.spyOn(backgroundApi,'progress').mockResolvedValue(running);const tasks=useTasksStore();expect(await tasks.probe.run({})).toBe(false);expect(tasks.probe.submitting).toBe(false);expect(tasks.probe.busy).toBe(true);expect(useToastStore().items[0]?.message).toBe('探测任务正在进行中');});
  it('cancel is not completion; duplicate cancels are locked and failed cancel does not claim success',async()=>{const wait=deferred<unknown>();const cancel=vi.spyOn(backgroundApi,'cancel').mockReturnValue(wait.promise);vi.spyOn(backgroundApi,'progress').mockResolvedValue(running);const tasks=useTasksStore();await tasks.scrape.restore();const first=tasks.scrape.cancel();await tasks.scrape.cancel();expect(cancel).toHaveBeenCalledTimes(1);expect(tasks.scrape.busy).toBe(true);wait.resolve({status:'cancelling'});await first;expect(tasks.revision).toBe(0);expect(tasks.scrape.busy).toBe(true);cancel.mockRejectedValueOnce(new ApiError('当前没有刮削任务',409));await tasks.scrape.cancel();expect(useToastStore().items.some(t=>t.message==='当前没有刮削任务')).toBe(true);expect(tasks.scrape.cancelling).toBe(false);});
  it('reset aborts in-flight application reads/submits and ignores late replies',async()=>{const write=deferred<{total:number;message:string}>(),read=deferred<typeof running>();const start=vi.spyOn(backgroundApi,'start').mockReturnValue(write.promise);const poll=vi.spyOn(backgroundApi,'progress').mockReturnValue(read.promise);const tasks=useTasksStore();const restore=tasks.scrape.restore(),submit=tasks.probe.run({});tasks.reset();expect(start.mock.calls[0]![3].aborted).toBe(true);expect(poll.mock.calls[0]![1].aborted).toBe(true);write.resolve({total:3,message:''});read.resolve(running);await Promise.all([restore,submit]);expect(tasks.mutationBusy).toBe(false);expect(tasks.revision).toBe(0);expect(tasks.probe.progress).toBeNull();expect(vi.getTimerCount()).toBe(0);});
  it('avatar payload uses the same scrape lifetime and cancelled completion remains visible',async()=>{const start=vi.spyOn(backgroundApi,'start').mockResolvedValue({total:3,message:''});vi.spyOn(backgroundApi,'progress').mockResolvedValue({...ended,kind:'scrape_avatars',cancelled:true,success:1});const tasks=useTasksStore();await tasks.scrape.run({library_id:2},true);expect(start.mock.calls[0]?.slice(0,3)).toEqual(['scrape',true,{library_id:2}]);expect(useToastStore().items.some(t=>t.message.includes('头像任务已中止'))).toBe(true);expect(tasks.scrape.visible).toBe(true);expect(tasks.revision).toBe(1);});
});
