<script setup lang="ts">
import {computed,onScopeDispose,ref,watch} from 'vue'; import {scheduledApi,type ScheduledPayload} from '../api/scheduled'; import {adminApi} from '../api/admin'; import {useAdminRead} from '../composables/useAdminRead'; import {useScheduledStore} from '../stores/scheduled'; import {useTasksStore} from '../stores/tasks'; import {useToastStore} from '../stores/toasts'; import ScheduledForm from '../components/scheduled/ScheduledForm.vue'; import ScheduledList from '../components/scheduled/ScheduledList.vue'; import ReadState from '../components/common/ReadState.vue';
const {data,error,loading,load,active}=useAdminRead(async signal=>{const [scheduled,libs]=await Promise.all([scheduledApi.list(signal),adminApi.libraries(signal)]); return {...scheduled,libraries:libs.items||[]};});
const state=useScheduledStore(),tasks=useTasksStore(),toasts=useToastStore(),submitting=ref(false),formKey=ref(0),busy=ref(new Set<string>()); const editing=computed(()=>data.value?.items.find(i=>i.id===state.editingId)||null);
const pending=new Map<number,string>(); let timer:ReturnType<typeof setTimeout>|undefined;
function schedule() {clearTimeout(timer); if(active()&&(pending.size||data.value?.items.some(i=>i.last_status==='running'))) timer=setTimeout(()=>{void load().finally(schedule);},1500);}
watch(data, value=>{if(!value)return; if(state.editingId&&!value.items.some(i=>i.id===state.editingId))state.editingId=null; for(const [id,before] of pending) {const item=value.items.find(i=>i.id===id); if(!item||(item.last_status!=='running'&&JSON.stringify([item.last_run_at,item.last_status,item.last_message])!==before)) {pending.delete(id);busy.value.delete('run:'+id);tasks.revision++;}} schedule();});
watch(()=>tasks.revision,()=>{void load();});
async function save(payload:ScheduledPayload) {if(submitting.value)return;const id=state.editingId;submitting.value=true;try{await scheduledApi.save(id,payload);toasts.show(id?'计划任务已保存':`计划任务「${payload.name}」已创建`);if(state.editingId===id)state.editingId=null;formKey.value++;if(active())await load();}catch(cause){toasts.show(cause instanceof Error?cause.message:'保存失败','error');}finally{submitting.value=false;}}
async function action(id:number,kind:'run'|'toggle'|'delete'|'edit') {if(kind==='edit'){state.editingId=id;return;}const key=kind+':'+id;if(busy.value.has(key)||(kind==='delete'&&!window.confirm('删除该计划任务？已产生的影片数据不受影响。')))return;busy.value.add(key);const item=data.value?.items.find(i=>i.id===id);try{await scheduledApi.action(id,kind);toasts.show(kind==='run'?'已触发执行，可在「任务」页查看结果':kind==='delete'?'计划任务已删除':'状态已更新');if(kind==='delete'&&state.editingId===id)state.editingId=null;if(kind==='run'){pending.set(id,JSON.stringify([item?.last_run_at,item?.last_status,item?.last_message]));void tasks.restoreAll();}if(active())await load();}catch(cause){toasts.show(cause instanceof Error?cause.message:'操作失败','error');if(active()&&kind==='toggle')await load();}finally{if(kind!=='run'||!pending.has(id))busy.value.delete(key);}}
onScopeDispose(()=>clearTimeout(timer));
</script>
<template><ReadState :error="error" :loading="loading" :empty="!data" @retry="load" /><template v-if="data"><ScheduledForm :key="formKey" :editing="editing" :libraries="data.libraries" :types="data.types" :submitting="submitting" @submit="save" @cancel-edit="state.editingId=null" /><ScheduledList :items="data.items" :busy="busy" :loading="loading" @action="action" @refresh="load" /></template></template>
