<script setup lang="ts">
import { onScopeDispose, ref, watch } from 'vue'; import { scrapeApi, type ScrapeSettings } from '../api/scrape'; import { adminApi } from '../api/admin'; import { useAdminRead } from '../composables/useAdminRead'; import { usePageRequest } from '../composables/usePageRequest'; import { useToastStore } from '../stores/toasts'; import { useTasksStore } from '../stores/tasks';
import ScrapeSettingsForm from '../components/scrape/ScrapeSettingsForm.vue'; import ScrapeRunPanel from '../components/scrape/ScrapeRunPanel.vue'; import ReadState from '../components/common/ReadState.vue';
const {data,error,loading,load,active} = useAdminRead(async signal => { const [settings, libs] = await Promise.all([scrapeApi.settings(signal),adminApi.libraries(signal)]); return {settings,libraries:libs.items || []}; });
const toasts = useToastStore(), tasks = useTasksStore(), saving = ref(false), testing = ref(new Set<string>()), count = ref<number|null>(null), countError = ref('');
const candidatesScope = usePageRequest(); let currentQuery: [number,boolean] = [0,true];
async function candidates(libraryId: number, onlyMissing: boolean) { currentQuery = [libraryId,onlyMissing]; const current = candidatesScope.begin(); count.value = null; countError.value = ''; try { const n = await scrapeApi.candidates(libraryId,onlyMissing,current.signal); if (current.isCurrent()) count.value = n; } catch (cause) { if (current.isCurrent()) countError.value = cause instanceof Error ? cause.message : '候选读取失败'; } }
async function save(value: ScrapeSettings) { if (saving.value) return; saving.value = true; try { const settings = await scrapeApi.save(value); toasts.show('配置已保存并即时生效'); if (active() && data.value) { data.value = {...data.value,settings}; void candidates(...currentQuery); } } catch (cause) { toasts.show(cause instanceof Error ? cause.message : '保存失败','error'); } finally { saving.value = false; } }
async function test(target:'metatube'|'translate') { if (testing.value.has(target)) return; testing.value.add(target); try { const r = await scrapeApi.test(target); toasts.show(r.ok ? `${r.detail}（${r.elapsed_ms}ms）` : `连接失败：${r.error}`, r.ok ? 'ok' : 'error'); } catch (cause) { toasts.show(cause instanceof Error ? cause.message : '测试失败','error'); } finally { testing.value.delete(target); } }
onScopeDispose(() => candidatesScope.cancel());
watch(() => tasks.revision, () => { void candidates(...currentQuery); });
</script>
<template><ReadState :error="error" :loading="loading" :empty="!data" @retry="load" /><template v-if="data"><ScrapeSettingsForm :settings="data.settings" :saving="saving" :testing="testing" @save="save" @test="test" /><ScrapeRunPanel :libraries="data.libraries" :count="count" :count-error="countError" @query="candidates" @run="tasks.scrape.run($event)" @avatar="tasks.scrape.run({library_id:$event}, true)" /></template></template>
